"use client";
import { useEffect,useMemo,useState,type FormEvent } from "react";
import { Plus,ShieldCheck,X } from "lucide-react";
type AiSystem={id:string;name:string;purpose:string;vendor:string;ownerName:string;riskTier:string;status:string;nextReviewAt:string|null};
export default function Home(){
 const [systems,setSystems]=useState<AiSystem[]>([]),[loading,setLoading]=useState(true),[formOpen,setFormOpen]=useState(false),[error,setError]=useState("");
 const metrics=useMemo(()=>({total:systems.length,high:systems.filter(x=>["high","prohibited"].includes(x.riskTier)).length,review:systems.filter(x=>x.status==="under_review").length,approved:systems.filter(x=>x.status==="approved").length}),[systems]);
 async function load(){setLoading(true);const r=await fetch("/api/systems");const d=await r.json() as {error?:string;systems?:AiSystem[]};if(!r.ok)throw new Error(d.error||"Unable to load systems");setSystems(d.systems||[]);setLoading(false)}
 useEffect(()=>{load().catch(e=>{setError(e.message);setLoading(false)})},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),body=Object.fromEntries(f);if(!body.nextReviewAt)body.nextReviewAt="";const r=await fetch("/api/systems",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json() as {error?:string};if(!r.ok){setError(d.error||"Unable to save system");return}e.currentTarget.reset();setFormOpen(false);await load()}
 return <main className="min-h-screen bg-[#f4f7f5] text-[#142b2d]">
  <header className="border-b border-[#dce6e1] bg-[#0a4d49] text-white"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 lg:px-10"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#c9f36b] font-black text-[#173a34]">G</span><div><p className="font-bold">GovernBright</p><p className="text-xs text-[#b8d5d1]">Private staging</p></div></div><div className="flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-sm"><ShieldCheck size={16}/>Protected workspace</div></div></header>
  <div className="mx-auto max-w-[1440px] px-5 py-8 lg:px-10"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="eyebrow">AI governance workspace</p><h1 className="text-3xl font-bold tracking-tight">System register</h1><p className="mt-2 text-[#667575]">Inventory AI tools, assign ownership, and track governance status.</p></div><button onClick={()=>setFormOpen(true)} className="flex items-center gap-2 rounded-xl bg-[#0f766e] px-4 py-3 font-bold text-white shadow-sm"><Plus size={18}/>Register system</button></div>
   <section className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total systems",metrics.total],["High risk",metrics.high],["Under review",metrics.review],["Approved",metrics.approved]].map(([l,v])=><article key={l} className="rounded-2xl border border-[#dfe6e2] bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-[#667575]">{l}</p><strong className="mt-2 block text-3xl">{v}</strong></article>)}</section>
   {error&&<p role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
   <section className="overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white shadow-sm"><div className="border-b border-[#e8eeeb] px-5 py-4"><h2 className="font-bold">Registered AI systems</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="bg-[#f7faf8] text-xs uppercase tracking-wider text-[#71807f]">{["System","Vendor","Owner","Risk","Status","Next review"].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{systems.map(s=><tr key={s.id} className="border-t border-[#edf1ef] text-sm"><td className="px-5 py-4 font-bold">{s.name}<span className="mt-1 block max-w-sm truncate font-normal text-[#71807f]">{s.purpose}</span></td><td className="px-5 py-4">{s.vendor}</td><td className="px-5 py-4">{s.ownerName}</td><td className="px-5 py-4"><Badge value={s.riskTier}/></td><td className="px-5 py-4"><Badge value={s.status}/></td><td className="px-5 py-4">{s.nextReviewAt||"—"}</td></tr>)}</tbody></table></div>{!loading&&!systems.length&&<div className="px-5 py-16 text-center"><p className="font-bold">No AI systems registered</p><p className="mt-1 text-sm text-[#71807f]">Register the first system to begin the governance inventory.</p></div>}{loading&&<div className="px-5 py-16 text-center text-sm text-[#71807f]">Loading workspace…</div>}</section>
  </div>
  {formOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#092f31]/45 p-4 backdrop-blur-sm"><section className="max-h-[92vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="eyebrow">New record</p><h2 className="text-2xl font-bold">Register AI system</h2></div><button aria-label="Close" onClick={()=>setFormOpen(false)} className="rounded-lg border border-[#dfe6e2] p-2"><X size={18}/></button></div><form onSubmit={submit} className="mt-6 grid gap-4"><Field label="System name" name="name"/><label>Purpose<textarea name="purpose" required/></label><div className="grid gap-4 sm:grid-cols-2"><Field label="Vendor" name="vendor"/><Field label="Business owner" name="ownerName"/></div><div className="grid gap-4 sm:grid-cols-2"><label>Risk tier<select name="riskTier" defaultValue="moderate"><option value="low">Low</option><option value="moderate">Moderate</option><option value="high">High</option><option value="prohibited">Prohibited</option></select></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="under_review">Under review</option><option value="approved">Approved</option></select></label></div><label>Next review date<input name="nextReviewAt" type="date"/></label><button className="mt-2 rounded-xl bg-[#0f766e] px-4 py-3 font-bold text-white">Save system</button></form></section></div>}
 </main>}
function Field({label,name}:{label:string;name:string}){return <label>{label}<input name={name} required/></label>}
function Badge({value}:{value:string}){const tone=["high","prohibited"].includes(value)?"red":["moderate","under_review"].includes(value)?"amber":["approved","low"].includes(value)?"green":"gray";return <span className={`badge ${tone}`}>{value.replace("_"," ")}</span>}
