import type { AiSystemService } from "../services/ai-systems.js";
import type { AuthService } from "../services/auth.js";
import type { MemberService } from "../services/members.js";
import type { MfaService } from "../services/mfa.js";
import type { OrganizationService } from "../services/organization.js";
import type { PasswordResetService } from "../services/password-reset.js";
import type { SsoService } from "../services/sso.js";
import type { PolicyService } from "../services/policies.js";
import type { AssessmentService } from "../services/assessments.js";
import type { ReportService } from "../services/reports.js";
import type { CatalogService } from "../services/catalog.js";
import type { DiscoveryService } from "../services/discovery.js";
import type { ProvisioningService } from "../services/provisioning.js";
import type { ToolRequestService } from "../services/tool-requests.js";
import type { ContactService } from "../services/contact.js";

export type Services = {
  aiSystems: AiSystemService;
  auth: AuthService;
  toolRequests: ToolRequestService;
  members: MemberService;
  mfa: MfaService;
  passwordReset: PasswordResetService;
  organization: OrganizationService;
  sso: SsoService;
  policies: PolicyService;
  assessments: AssessmentService;
  reports: ReportService;
  catalog: CatalogService;
  discovery: DiscoveryService;
  provisioning: ProvisioningService;
  contact: ContactService;
};
