import { randomUUID } from "node:crypto";
import { and,desc,eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { approvedUsers,auditEvents,toolRequests } from "../../../db/schema";
function viewer(r:Request){const userId=r.headers.get("oai-authenticated-user-id"),email=r.headers.get("oai-authenticated-user-email")?.toLowerCase();if(!userId||!email)throw new Error("Authentication required");return {userId,email}}
async function administrator(email:string){const rows=await getDb().select().from(approvedUsers).where(and(eq(approvedUsers.email,email),eq(approvedUsers.role,"admin"),eq(approvedUsers.status,"approved"))).limit(1);return rows[0]??null}
export async function GET(r:Request){try{const v=viewer(r),admin=await administrator(v.email),db=getDb();const rows=admin?await db.select().from(toolRequests).where(eq(toolRequests.organizationId,admin.organizationId)).orderBy(desc(toolRequests.requestedAt)):await db.select().from(toolRequests).where(eq(toolRequests.requesterUserId,v.userId)).orderBy(desc(toolRequests.requestedAt));return Response.json({requests:rows,isAdmin:!!admin})}catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to load requests"},{status:500})}}
export async function POST(r:Request){try{const v=viewer(r),p=await r.json() as Record<string,string>,toolName=p.toolName?.trim().slice(0,120),purpose=p.businessPurpose?.trim().slice(0,2000);if(!toolName||!purpose)return Response.json({error:"Tool name and business purpose are required"},{status:400});const db=getDb(),admins=await db.select().from(approvedUsers).where(eq(approvedUsers.role,"admin")).limit(1);if(!admins[0])return Response.json({error:"An administrator must initialize GovernBright first"},{status:409});const now=new Date().toISOString(),id=randomUUID(),toolKey=toolName.toLowerCase().includes("chatgpt")?"chatgpt":toolName.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");await db.batch([db.insert(toolRequests).values({id,organizationId:admins[0].organizationId,requesterUserId:v.userId,requesterEmail:v.email,toolKey,toolName,businessPurpose:purpose,dataDescription:p.dataDescription?.trim().slice(0,2000)||"",status:"pending",requestedAt:now}),db.insert(auditEvents).values({id:randomUUID(),organizationId:admins[0].organizationId,actorUserId:v.userId,action:"ai_tool.requested",targetType:"tool_request",targetId:id,metadata:JSON.stringify({toolName,email:v.email}),createdAt:now})]);return Response.json({requestId:id,status:"pending"},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to submit request"},{status:500})}}
export async function PATCH(r:Request){try{const v=viewer(r),admin=await administrator(v.email);if(!admin)return Response.json({error:"Administrator approval required"},{status:403});const p=await r.json() as {id?:string;decision?:string;notes?:string};if(!p.id||!["approved","rejected"].includes(p.decision||""))return Response.json({error:"Request and decision are required"},{status:400});const db=getDb(),now=new Date().toISOString();await db.batch([db.update(toolRequests).set({status:p.decision as "approved"|"rejected",decidedBy:v.userId,decisionNotes:p.notes?.trim().slice(0,1000)||"",decidedAt:now}).where(and(eq(toolRequests.id,p.id),eq(toolRequests.organizationId,admin.organizationId))),db.insert(auditEvents).values({id:randomUUID(),organizationId:admin.organizationId,actorUserId:v.userId,action:`ai_tool.${p.decision}`,targetType:"tool_request",targetId:p.id,metadata:JSON.stringify({notes:p.notes||""}),createdAt:now})]);return Response.json({updated:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to decide request"},{status:500})}}
